[info] Running main.scala.WordLinker 
[debug] Starting sandboxed run...
[debug] Waiting for threads to exit or System.exit to be called.
[debug]   Classpath:
[debug] 	/home/lieslw/WordLinks/target/scala-2.9.1/classes
[debug] 	/home/lieslw/WordLinks/lib/libsvm.jar
[debug] 	/home/lieslw/WordLinks/lib/Jama-1.0.2.jar
[debug] 	/home/lieslw/WordLinks/lib/commons-math-1.2.jar
[debug] 	/home/lieslw/WordLinks/lib/weka.jar
[debug] 	/home/lieslw/WordLinks/lib/javaml-0.1.6.jar
[debug] 	/home/lieslw/WordLinks/lib/ajt-2.5.jar
[debug] 	/home/lieslw/.sbt/boot/scala-2.9.1/lib/scala-library.jar
[debug] 	/home/lieslw/.ivy2/cache/com.twitter/finagle-core_2.9.1/jars/finagle-core_2.9.1-1.9.12.jar
[debug] 	/home/lieslw/.ivy2/cache/com.twitter/util-core_2.9.1/jars/util-core_2.9.1-1.12.9.jar
[debug] 	/home/lieslw/.ivy2/cache/org.jboss.netty/netty/bundles/netty-3.2.7.Final.jar
[debug] 	/home/lieslw/.ivy2/cache/com.twitter/util-collection_2.9.1/jars/util-collection_2.9.1-1.12.9.jar
[debug] 	/home/lieslw/.ivy2/cache/commons-collections/commons-collections/jars/commons-collections-3.2.1.jar
[debug] 	/home/lieslw/.ivy2/cache/com.google.guava/guava/jars/guava-r09.jar
[debug] 	/home/lieslw/.ivy2/cache/com.twitter/util-hashing_2.9.1/jars/util-hashing_2.9.1-1.12.9.jar
[debug] 	/home/lieslw/.ivy2/cache/com.twitter/finagle-http_2.9.1/jars/finagle-http_2.9.1-1.9.12.jar
[debug] 	/home/lieslw/.ivy2/cache/com.twitter/util-logging_2.9.1/jars/util-logging_2.9.1-1.12.9.jar
[debug] 	/home/lieslw/.ivy2/cache/com.twitter/util-codec_2.9.1/jars/util-codec_2.9.1-1.12.9.jar
[debug] 	/home/lieslw/.ivy2/cache/commons-codec/commons-codec/jars/commons-codec-1.5.jar
[debug] 	/home/lieslw/.ivy2/cache/commons-lang/commons-lang/jars/commons-lang-2.6.jar
[debug] Waiting for thread run-main to exit
[error] (run-main) com.twitter.finagle.ChannelClosedException: ChannelException at remote address: rk-laptop.local/134.197.34.120:2984
com.twitter.finagle.ChannelClosedException: ChannelException at remote address: rk-laptop.local/134.197.34.120:2984
	at com.twitter.finagle.NoStacktrace(Unknown Source)
[debug] 	Thread run-main exited.
[debug] Waiting for thread FinagleClientBoss-1 to exit
[debug] 	Thread FinagleClientBoss-1 exited.
[debug] Waiting for thread FinagleClientIO-1 to exit
[debug] 	Thread FinagleClientIO-1 exited.
[debug] Interrupting remaining threads (should be all daemons).
[debug] Sandboxed run complete..
java.lang.RuntimeException: Nonzero exit code: 1
	at scala.sys.package$.error(package.scala:27)
	at sbt.BuildCommon$$anonfun$toError$1.apply(Defaults.scala:1166)
	at sbt.BuildCommon$$anonfun$toError$1.apply(Defaults.scala:1166)
	at scala.Option.foreach(Option.scala:197)
	at sbt.BuildCommon$class.toError(Defaults.scala:1166)
	at sbt.Defaults$.toError(Defaults.scala:32)
	at sbt.Defaults$$anonfun$runTask$1$$anonfun$apply$22.apply(Defaults.scala:430)
	at sbt.Defaults$$anonfun$runTask$1$$anonfun$apply$22.apply(Defaults.scala:428)
	at sbt.Scoped$$anonfun$hf5$1.apply(Structure.scala:476)
	at sbt.Scoped$$anonfun$hf5$1.apply(Structure.scala:476)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:41)
	at sbt.Scoped$Reduced$$anonfun$combine$1$$anonfun$apply$11.apply(Structure.scala:295)
	at sbt.Scoped$Reduced$$anonfun$combine$1$$anonfun$apply$11.apply(Structure.scala:295)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$5.work(System.scala:67)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:221)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:221)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
	at sbt.Execute.work(Execute.scala:227)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:221)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:221)
	at sbt.CompletionService$$anon$1$$anon$2.call(CompletionService.scala:26)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:722)
[error] {file:/home/lieslw/WordLinks/}default-528e04/compile:run: Nonzero exit code: 1
